/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedSharedWithMeRouteImport } from './routes/_authed.shared-with-me'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as SharedTokenIndexRouteImport } from './routes/shared.$token.index'
import { Route as SharedTokenItemIdRouteImport } from './routes/shared.$token.$itemId'
import { Route as AuthedRoomsRoomIdIndexRouteImport } from './routes/_authed.rooms.$roomId.index'
import { Route as AuthedRoomsRoomIdItemIdRouteImport } from './routes/_authed.rooms.$roomId.$itemId'
import { Route as AuthedRoomsRoomIdTrashRouteImport } from './routes/_authed.rooms.$roomId.trash'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSharedWithMeRoute = AuthedSharedWithMeRouteImport.update({
  id: '/shared-with-me',
  path: '/shared-with-me',
  getParentRoute: () => AuthedRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenIndexRoute = SharedTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedTokenRoute,
} as any)
const SharedTokenItemIdRoute = SharedTokenItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => SharedTokenRoute,
} as any)
const AuthedRoomsRoomIdIndexRoute = AuthedRoomsRoomIdIndexRouteImport.update({
  id: '/rooms/$roomId/',
  path: '/rooms/$roomId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsRoomIdItemIdRoute = AuthedRoomsRoomIdItemIdRouteImport.update({
  id: '/rooms/$roomId/$itemId',
  path: '/rooms/$roomId/$itemId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsRoomIdTrashRoute = AuthedRoomsRoomIdTrashRouteImport.update({
  id: '/rooms/$roomId/trash',
  path: '/rooms/$roomId/trash',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shared-with-me': typeof AuthedSharedWithMeRoute
  '/shared/$token': typeof SharedTokenRouteWithChildren
  '/shared/$token/$itemId': typeof SharedTokenItemIdRoute
  '/shared/$token/': typeof SharedTokenIndexRoute
  '/rooms/$roomId/$itemId': typeof AuthedRoomsRoomIdItemIdRoute
  '/rooms/$roomId/trash': typeof AuthedRoomsRoomIdTrashRoute
  '/rooms/$roomId/': typeof AuthedRoomsRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shared-with-me': typeof AuthedSharedWithMeRoute
  '/': typeof AuthedIndexRoute
  '/shared/$token/$itemId': typeof SharedTokenItemIdRoute
  '/shared/$token': typeof SharedTokenIndexRoute
  '/rooms/$roomId/$itemId': typeof AuthedRoomsRoomIdItemIdRoute
  '/rooms/$roomId/trash': typeof AuthedRoomsRoomIdTrashRoute
  '/rooms/$roomId': typeof AuthedRoomsRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/shared-with-me': typeof AuthedSharedWithMeRoute
  '/shared/$token': typeof SharedTokenRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/shared/$token/$itemId': typeof SharedTokenItemIdRoute
  '/shared/$token/': typeof SharedTokenIndexRoute
  '/_authed/rooms/$roomId/$itemId': typeof AuthedRoomsRoomIdItemIdRoute
  '/_authed/rooms/$roomId/trash': typeof AuthedRoomsRoomIdTrashRoute
  '/_authed/rooms/$roomId/': typeof AuthedRoomsRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/shared-with-me'
    | '/shared/$token'
    | '/shared/$token/$itemId'
    | '/shared/$token/'
    | '/rooms/$roomId/$itemId'
    | '/rooms/$roomId/trash'
    | '/rooms/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/shared-with-me'
    | '/'
    | '/shared/$token/$itemId'
    | '/shared/$token'
    | '/rooms/$roomId/$itemId'
    | '/rooms/$roomId/trash'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/shared-with-me'
    | '/shared/$token'
    | '/_authed/'
    | '/shared/$token/$itemId'
    | '/shared/$token/'
    | '/_authed/rooms/$roomId/$itemId'
    | '/_authed/rooms/$roomId/trash'
    | '/_authed/rooms/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SharedTokenRoute: typeof SharedTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shared-with-me': {
      id: '/_authed/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof AuthedSharedWithMeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token/': {
      id: '/shared/$token/'
      path: '/'
      fullPath: '/shared/$token/'
      preLoaderRoute: typeof SharedTokenIndexRouteImport
      parentRoute: typeof SharedTokenRoute
    }
    '/shared/$token/$itemId': {
      id: '/shared/$token/$itemId'
      path: '/$itemId'
      fullPath: '/shared/$token/$itemId'
      preLoaderRoute: typeof SharedTokenItemIdRouteImport
      parentRoute: typeof SharedTokenRoute
    }
    '/_authed/rooms/$roomId/': {
      id: '/_authed/rooms/$roomId/'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof AuthedRoomsRoomIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/$roomId/$itemId': {
      id: '/_authed/rooms/$roomId/$itemId'
      path: '/rooms/$roomId/$itemId'
      fullPath: '/rooms/$roomId/$itemId'
      preLoaderRoute: typeof AuthedRoomsRoomIdItemIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/$roomId/trash': {
      id: '/_authed/rooms/$roomId/trash'
      path: '/rooms/$roomId/trash'
      fullPath: '/rooms/$roomId/trash'
      preLoaderRoute: typeof AuthedRoomsRoomIdTrashRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSharedWithMeRoute: typeof AuthedSharedWithMeRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedRoomsRoomIdItemIdRoute: typeof AuthedRoomsRoomIdItemIdRoute
  AuthedRoomsRoomIdTrashRoute: typeof AuthedRoomsRoomIdTrashRoute
  AuthedRoomsRoomIdIndexRoute: typeof AuthedRoomsRoomIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSharedWithMeRoute: AuthedSharedWithMeRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedRoomsRoomIdItemIdRoute: AuthedRoomsRoomIdItemIdRoute,
  AuthedRoomsRoomIdTrashRoute: AuthedRoomsRoomIdTrashRoute,
  AuthedRoomsRoomIdIndexRoute: AuthedRoomsRoomIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface SharedTokenRouteChildren {
  SharedTokenItemIdRoute: typeof SharedTokenItemIdRoute
  SharedTokenIndexRoute: typeof SharedTokenIndexRoute
}

const SharedTokenRouteChildren: SharedTokenRouteChildren = {
  SharedTokenItemIdRoute: SharedTokenItemIdRoute,
  SharedTokenIndexRoute: SharedTokenIndexRoute,
}

const SharedTokenRouteWithChildren = SharedTokenRoute._addFileChildren(
  SharedTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SharedTokenRoute: SharedTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
